// frontend/src/components/LoadMoreButton.vue
<template>
  <div class="mt-3">
    <button v-if="hasMore" @click="$emit('click')" class="btn-primary w-full flex items-center justify-center gap-2">
      <span v-if="!isLoading">{{ label || 'Load More' }}</span>
      <span v-else>Loading...</span>
    </button>
  </div>
</template>

<script setup>
defineProps({ isLoading: Boolean, hasMore: Boolean, label: String })
</script>

// angular-frontend/src/app/components/load-more-button/load-more-button.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';

@Component({
  selector: 'app-load-more-button',
  standalone: true,
  template: `
    <div class="mt-3">
      @if (hasMore) {
        <button (click)="clicked.emit()" class="btn-primary w-full flex items-center justify-center gap-2">
          {{ isLoading ? 'Loading...' : label }}
        </button>
      }
    </div>
  `,
})
export class LoadMoreButtonComponent {
  @Input() hasMore = false;
  @Input() isLoading = false;
  @Input() label = 'Load More';
  @Output() clicked = new EventEmitter<void>();
}
